website/models.py
from flask_login import UserMixin
from datetime import datetime
from website import db

class User_Checkout(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    username = db.Column(db.String(150))
    name = db.Column(db.String(150))  
    address = db.Column(db.String(300))  
    phone = db.Column(db.String(20))  
    balance = db.Column(db.Float, nullable=False, default=100000)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    username = db.Column(db.String(150))
    name = db.Column(db.String(150), default = 'Lorem Ipsum')  
    address = db.Column(db.String(300), default = 'Lorem Ipsum Address')  
    phone = db.Column(db.String(20) , default= '0987654321')  
    balance = db.Column(db.Float, nullable=False, default=100000)

    orders = db.relationship("Order", back_populates="user")

    cart_id = db.Column(db.Integer, db.ForeignKey('cart.id'), nullable=True)
    cart = db.relationship('Cart', backref=db.backref('users', lazy=True), foreign_keys=[cart_id])

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300), nullable=False)
    price = db.Column(db.Integer, nullable=False)
    rating = db.Column(db.Float, nullable=False)
    review_count = db.Column(db.Integer)
    description = db.Column(db.String(1000))
    image = db.Column(db.String(150), nullable=False)
    url = db.Column(db.String(300), nullable=False)
    category = db.Column(db.String(150), nullable=False)

    def generate_url(self):
        # Generate a URL-friendly version of the product name
        return f"{self.name.replace(' ', '-').lower()}"

    @staticmethod
    def create_product(name, price, rating, review_count, description, image, category):
        product = Product(
            name=name,
            price=price,
            rating=rating,
            review_count=review_count,
            description=description,
            image=image,
            category=category
        )
        product.url = product.generate_url()
        return product

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    total_quantity = db.Column(db.Integer, nullable=False, default=0)
    total_price = db.Column(db.Integer, nullable=False, default=0)
    items = db.relationship('CartItem', backref='cart', lazy=True) 

    def update_totals(self):
        self.total_quantity = sum(item.quantity for item in self.items)
        self.total_price = sum(item.quantity * item.product.price for item in self.items)
        db.session.commit()

class CartItem(db.Model): 
    id = db.Column(db.Integer, primary_key=True) 
    cart_id = db.Column(db.Integer, db.ForeignKey('cart.id'), nullable=False) 
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False) 
    size = db.Column(db.String(5))
    quantity = db.Column(db.Integer, nullable=False, default=1) 
    product = db.relationship('Product')

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    order_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    status = db.Column(db.String(50), nullable=False, default='Pending')
    total_price = db.Column(db.Float, nullable=False, default=0.0)

    items = db.relationship('OrderItem', backref='order', lazy=True)
    user = db.relationship("User", back_populates="orders")

    email = db.Column(db.String(150), unique=True)
    name = db.Column(db.String(150))  
    address = db.Column(db.String(300))  
    phone = db.Column(db.String(20))  

class OrderItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False)
    quantity = db.Column(db.Integer, nullable=False, default=1)
    size = db.Column(db.String(10), nullable=False)
    price = db.Column(db.Float, nullable=False)

class Payment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
    amount = db.Column(db.Float, nullable=False)
    payment_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    status = db.Column(db.String(50), nullable=False, default='Completed')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

db = SQLAlchemy()
DB_NAME = "database.db"

class UserModelView(ModelView):
    column_list = ('id', 'email', 'password','username')

class ProductModelView(ModelView):
    column_list = ('id', 'name', 'price', 'rating', 'review_count', 'description', 'image', 'category')

class CartModelView(ModelView):
    column_list = ('id', 'user_id', 'total_quantity', 'total_price')

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'alonewolfs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}?timeout=15'
    db.init_app(app)
    admin = Admin(app)

    from .views import views
    from .account import account_bp
    from .about import about_bp
    from .cart import cart_bp
    from .contact import contact_bp
    from .pd import pd_bp
    from .products import products_bp
    from .checkout import checkout_bp

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(account_bp, url_prefix='/')
    app.register_blueprint(about_bp, url_prefix='/')
    app.register_blueprint(cart_bp, url_prefix='/')
    app.register_blueprint(contact_bp, url_prefix='/')
    app.register_blueprint(pd_bp, url_prefix='/')
    app.register_blueprint(products_bp, url_prefix='/')
    app.register_blueprint(checkout_bp, url_prefix='/')

    from .models import User, Product, Cart

    admin.add_view(UserModelView(User, db.session))
    admin.add_view(ProductModelView(Product, db.session))
    admin.add_view(CartModelView(Cart, db.session, endpoint='admin_cart'))

    create_database(app)

    login_manager = LoginManager()
    # login_manager.login_view = 'account.home'
    login_manager.init_app(app)

    @login_manager.user_loader
    def login_manager(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created Database!')

website/views.py
from flask import Blueprint, render_template
from flask_login import login_user, login_required, current_user

from website.models import Product

views = Blueprint('views', __name__)

@views.route('/')
# @login_required
def home():
    # Lấy ra 4 sản phẩm có lượng review_count cao nhất
    top_reviewed_products = Product.query.order_by(Product.review_count.desc()).limit(4).all()

    # Lấy ra 4 sản phẩm có rating cao nhất
    top_rated_products = Product.query.order_by(Product.rating.desc()).limit(4).all()
    return render_template("home.html", top_rated_products = top_rated_products, top_reviewed_products = top_reviewed_products)

website/templates/about.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About - AWS</title>
    <link rel="stylesheet" href="../static/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <a href="{{ url_for('views.home') }}"><img src="../static/images/logo.png" width="125px"></a>
            </div>
            <nav>
                <ul id="MenuItems">
                    <li><a href="{{ url_for('views.home') }}">Home</a></li>
                    <li><a href="{{ url_for('products.home') }}">Products</a></li>
                    <li><a href="{{ url_for('about.home') }}">About</a></li>
                    <li><a href="{{ url_for('contact.home') }}">Contact</a></li>
                    <li><a href="{{ url_for('account.redirect_account') }}">Account</a></li>
                    <li><a href="{{ url_for('account.redirect_account') }}">User Account</a></li>
                </ul>
            </nav>
            <a href="{{ url_for('cart.home') }}"><img src="../static/images/cart.png" width="30px" height="30px"></a>
            <img src="../static/images/menu.png" class="menu-icon" onClick="menutoggle()">
        </div>
    </div>

    <div class="small-container about-page">
        <div class="row">
            <div class="col-2">
                <img src="../static/images/basketball.png" alt="About Us">
            </div>
            <div class="col-2 col-2-text">
                <h3>About Us</h3>
                <p>We are a team passionate about sports and technology, with the goal of bringing the best products and services to our customers. At AWS, we believe that sports are not just an activity, but a lifestyle. We continually strive to provide the best experiences for our customers.</p>                
                
                <h3>Our Mission</h3>
                <p>Our mission is to provide high-quality products and services that meet customer needs and contribute to improving the quality of life through sports.</p>
                
                <h3>Our Vision</h3>
                <p>We aim to become a leading brand in the field of sports and technology, continuously innovating and creating sustainable value for our customers and the community.</p>
            </div>
        </div>
    </div>

    <!----------------------------------footer-------------------------------------->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-2">
                    <img src="../static/images/logo-white.png" alt="AWS Logo">
                    <p>Sports is not just an activity, but also a lifestyle.</p>
                </div>
                <div class="footer-col-4">
                    <h3>Follow us</h3>
                    <ul>
                        <li><a href="https://github.com/SmrfHdl" target="_blank">Phạm Văn Trường</a></li>
                        <li><a href="https://github.com/UETER2226" target="_blank">Đỗ Quang Dũng</a></li>
                        <li><a href="https://github.com/hieu7404" target="_blank">Lê Trung Hiếu</a></li>
                        <li><a href="https://github.com/angWindy" target="_blank">Trần An Thắng</a></li>
                    </ul>
                </div>
            </div>
            <hr>
            <p class="copyright">Alone Wolf Team</p>
        </div>
    </div>

    <!-----------------------------------js for toggle menu------------------------------------------------>
    <script>
        var menuItems=document.getElementById("MenuItems");
        
        MenuItems.style.maxHeight="0px";
        function menutoggle(){
            if(MenuItems.style.maxHeight == "0px"){
                MenuItems.style.maxHeight="200px";
            }
            else{
                MenuItems.style.maxHeight="0px";
            }
        }
    </script>
</body>

</html>

website/templates/account.html
<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width-device-width, initial-scale=1.0">
        <title>Account - AWS</title>
        <link rel="stylesheet" href="../static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
        <!--added a cdn link by searching font awesome4 cdn and getting this link from https://www.bootstrapcdn.com/fontawesome/ this url*/-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <!--<div class ="header">-->
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="{{ url_for('views.home') }}"><img src="../static/images/logo.png" width="125px"></a>
                </div>
                 <nav>
                    <ul id="MenuItems">
                        <li><a href="{{ url_for('views.home') }}">Home</a></li>
                        <li><a href="{{ url_for('products.home') }}">Products</a></li>
                        <li><a href="{{ url_for('about.home') }}">About</a></li>
                        <li><a href="{{ url_for('contact.home') }}">Contact</a></li>
                        <li><a href="{{ url_for('account.redirect_account') }}">Account</a></li>
                        <li><a href= "{{ url_for('account.redirect_account')}}">User Account</a></li>
                    </ul>
                </nav>
                <a href="{{ url_for('cart.home') }}"><img src="../static/images/cart.png" width="30px" height="30px"></a>
                <img src="../static/images/menu.png" class="menu-icon" onClick="menutoggle()" >
            </div>
           
        </div>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% else %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% endwith %}
    <!--</div>-->
        
        <!------------------------------ account-page details------------------------------>

        <div class="account-page">
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        <img src="../static/images/image1.png" width="100%">
                    </div>
                    <div class="col-2">
                        <div class="form-container">
                            <div class="form-btn">
                                <span onclick="login()">Login</span>
                                <span onclick="register()">Register</span>
                                <hr id="Indicator">
                            </div>
                            <form id="LoginForm" method="POST">
                                <input type="text" name="username" placeholder="username">
                                <input type="password" name="password" placeholder="password">
                                <input type="hidden" name="action" value="login">
                                <button type="submit" class="btn">Login</button>
                                <a href="">Create account</a>
                            </form>
                            
                            <form id="RegForm" method="POST">
                                <input type="text" name="username" placeholder="username">
                                <input type="email" name="email" placeholder="email">
                                <input type="password" name="password" placeholder="password">
                                <input type="hidden" name="action" value="register">
                                <button type="submit" class="btn">Register</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
       
        <!----------------------------------footer-------------------------------------->
        <div class ="footer">
            <div class="container">
                
                <div class="row">
                    <div class="footer-col-2">
                        <img src="../static/images/logo-white.png">
                        <p>Sports is not just an activity, but also a lifestyle.</p>
                    </div>
                    <div class="footer-col-4">
                        <h3>Follow us</h3>
                       <ul>
                        <li><a href="https://github.com/SmrfHdl" target="_blank">Phạm Văn Trường</a></li>
                            <li><a href="https://github.com/UETER2226" target="_blank">Đỗ Quang Dũng</a></li>
                            <li><a href="https://github.com/hieu7404" target="_blank">Lê Trung Hiếu</a></li>
                            <li><a href="https://github.com/angWindy" target="_blank">Trần An Thắng</a></li>                    
                        </ul>
                    </div>
                    
                </div>
                
                <hr><!--horizontal line-->
                <p class="copyright">Alone Wolf Team</p>
                
            </div>
        </div>
        
        
        <!-----------------------------------js for toggle menu-------------------------------------->
        <script>
            var menuItems=document.getElementById("MenuItems");
            
            MenuItems.style.maxHeight="0px";
            function menutoggle(){
                if(MenuItems.style.maxHeight == "0px"){
                    MenuItems.style.maxHeight="200px";
                }
                else{
                    MenuItems.style.maxHeight="0px";
                }
            }
        </script>
        
        <!-----------------------------------js for toggle form-------------------------------------->
        <script>
            var LoginForm=document.getElementById("LoginForm");
            var RegForm=document.getElementById("RegForm");
            var Indicator=document.getElementById("Indicator");
            
            function register(){
                RegForm.style.transform="translateX(0px)";
                LoginForm.style.transform="translateX(0px)";
                Indicator.style.transform="translateX(100px)"
            }
            function login(){
                RegForm.style.transform="translateX(300px)";
                LoginForm.style.transform="translateX(300px)";
                Indicator.style.transform="translateX(0px)";
            }
        </script>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>    

    </body>
</html>

website/templates/cart.html
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width-device-width, initial-scale=1.0" />
  <title>Cart - AWS</title>
  <link rel="stylesheet" href="../static/style.css" />
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  />
</head>

<body>
  <div class="container">
    <div class="navbar">
      <div class="logo">
        <a href="{{ url_for('views.home') }}"
          ><img src="../static/images/logo.png" width="125px"
        /></a>
      </div>
      <nav>
        <ul id="MenuItems">
          <li><a href="{{ url_for('views.home') }}">Home</a></li>
          <li><a href="{{ url_for('products.home') }}">Products</a></li>
          <li><a href="{{ url_for('about.home') }}">About</a></li>
          <li><a href="{{ url_for('contact.home') }}">Contact</a></li>
          <li>
            <a href="{{ url_for('account.redirect_account') }}">Account</a>
          </li>
          <li>
            <a href="{{ url_for('account.redirect_account') }}"
              >User Account</a
            >
          </li>
        </ul>
      </nav>
      <a href="{{ url_for('cart.home') }}"
        ><img src="../static/images/cart.png" width="30px" height="30px"
      /></a>
      <img
        src="../static/images/menu.png"
        class="menu-icon"
        onClick="menutoggle()"
      />
    </div>
  </div>

  <div class="small-container cart-page">
    {% if cart.items %}
    <table>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Size</th>
        <th>Subtotal</th>
      </tr>

      {% for item in cart.items %}
      <tr class="cart-item" data-item-id="{{ item.id }}">
        <td>
          <div class="cart-info">
            <img src="{{item.product.image}}" />
            <div>
              <p>{{item.product.name}}</p>
              <small class="product-price"
                >Price: ${{ '%.2f' | format(item.product.price) }}</small
              ><br />
              <a href="#" class="remove-btn">Remove</a>
            </div>
          </div>
        </td>
        <td>
          <input
            type="number"
            value="{{ item.quantity }}"
            class="quantity-input"
            min="1"
          />
        </td>
        <td class="size">{{item.size}}</td>
        <td class="subtotal">${{ '%.2f' | format(item.product.price * item.quantity) }}</td>
      </tr>
      {% endfor %}
    </table>

    <div class="total-price">
      <table>
        <tr>
          <td>Total</td>
          <td class="subtotal-price">${{ '%.2f' | format(cart.total_price) }}</td>
        </tr>
        <tr>
          <td>
            <a href="{{ url_for('checkout.home') }}" class="btn">Payment</a>
          </td>
        </tr>
      </table>
    </div>
    {% else %}
    <p>Your cart is empty.</p>
    <a href="{{ url_for('products.home') }}" class="btn">Continue Shopping</a>
    {% endif %}
  </div>
  <!----------------------------------footer-------------------------------------->
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="footer-col-2">
          <img src="../static/images/logo-white.png" />
          <p>Sports is not just an activity, but also a lifestyle.</p>
        </div>
        <div class="footer-col-4">
          <h3>Follow us</h3>
          <ul>
            <li>
              <a href="https://github.com/SmrfHdl" target="_blank"
                >Phạm Văn Trường</a
              >
            </li>
            <li>
              <a href="https://github.com/UETER2226" target="_blank"
                >Đỗ Quang Dũng</a
              >
            </li>
            <li>
              <a href="https://github.com/hieu7404" target="_blank"
                >Lê Trung Hiếu</a
              >
            </li>
            <li>
              <a href="https://github.com/angWindy" target="_blank"
                >Trần An Thắng</a
              >
            </li>
          </ul>
        </div>
      </div>

      <hr />
      <!--horizontal line-->
      <p class="copyright">Alone Wolf Team</p>
    </div>
  </div>

  <!----------------------------------script for cart-------------------------------------->
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const quantityInputs = document.querySelectorAll(".quantity-input");
      const subtotalPriceElement = document.querySelector(".subtotal-price");
      const totalPriceElement = document.querySelector(".total-price-value");

      quantityInputs.forEach((input) => {
        input.addEventListener("change", function () {
          const cartItem = this.closest(".cart-item");
          const itemId = cartItem.dataset.itemId;
          const newQuantity = this.value;

          updateQuantity(itemId, newQuantity, cartItem);
        });
      });

      document.querySelectorAll(".remove-btn").forEach((button) => {
        button.addEventListener("click", function (event) {
          event.preventDefault(); // Ngăn chặn hành động mặc định của nút "Remove"

          const cartItem = this.closest(".cart-item"); // Tìm phần tử cha chứa mục giỏ hàng
          const itemId = cartItem.dataset.itemId;

          removeItem(itemId, cartItem);
        });
      });

      function updateQuantity(itemId, newQuantity, cartItem) {
        fetch(`/cart/update_quantity`, {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
          },
          body: `item_id=${itemId}&quantity=${newQuantity}`,
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === "success") {
              const priceElement = cartItem.querySelector(".product-price");
              const price = parseFloat(
                priceElement.textContent.replace("Price: $", "")
              );
              const subtotalElement = cartItem.querySelector(".subtotal");
              const itemSubtotal = price * newQuantity;
              subtotalElement.textContent = `$${itemSubtotal.toFixed(2)}`;

              updateCartTotals();
            }
          });
      }

      function removeItem(itemId, cartItem) {
        fetch(`/cart/remove_item/${itemId}`, {
          method: "GET",
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === "success") {
              cartItem.remove();
              updateCartTotals();
            }
          });
      }

      function updateCartTotals() {
        let subtotal = 0;

        document.querySelectorAll(".cart-item").forEach((cartItem) => {
          const subtotalElement = cartItem.querySelector(".subtotal");
          const itemSubtotal = parseFloat(
            subtotalElement.textContent.replace("$", "")
          );
          subtotal += itemSubtotal;
        });

        subtotalPriceElement.textContent = `$${subtotal.toFixed(2)}`;
        totalPriceElement.textContent = `$${subtotal.toFixed(2)}`;
      }

      // Initial calculation
      updateCartTotals();
    });
  </script>
  <!-----------------------------------js for toggle menu------------------------------------------------>
  <script>
    var menuItems = document.getElementById("MenuItems");

    MenuItems.style.maxHeight = "0px";
    function menutoggle() {
      if (MenuItems.style.maxHeight == "0px") {
        MenuItems.style.maxHeight = "200px";
      } else {
        MenuItems.style.maxHeight = "0px";
      }
    }
  </script>
</body>
</html>

website/templates/confirmation.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation - AWS</title>
    <link rel="stylesheet" href="../static/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <a href="{{ url_for('views.home') }}"><img src="../static/images/logo.png" width="125px"></a>
            </div>
            <nav>
                <ul id="MenuItems">
                    <li><a href="{{ url_for('views.home') }}">Home</a></li>
                    <li><a href="{{ url_for('products.home') }}">Products</a></li>
                    <li><a href="{{ url_for('about.home') }}">About</a></li>
                    <li><a href="{{ url_for('contact.home') }}">Contact</a></li>
                    <li><a href="{{ url_for('account.home') }}">Account</a></li>
                </ul>
            </nav>
            <a href="{{ url_for('cart.home') }}"><img src="../static/images/cart.png" width="30px" height="30px"></a>
            <img src="../static/images/menu.png" class="menu-icon" onClick="menutoggle()">
        </div>
    </div>

    <div class="small-container confirmation-page">
        <p><br><p>
        <h2>Thank you for your purchase!</h2>
        <div class="confirmation-details">
            <p><br>Your order has been processed successfully.</p>
            <p>A confirmation email has been sent to your email address.</p>
        </div>
        <a href="{{ url_for('products.home') }}" class="btn">Continue shopping</a>
        <p><br><br><br><br><br><br><br><p>
    </div>

    <!----------------------------------footer-------------------------------------->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-2">
                    <img src="../static/images/logo-white.png">
                    <p>Sports is not just an activity, but also a lifestyle.</p>
                </div>
                <div class="footer-col-4">
                    <h3>Follow us</h3>
                    <ul>
                        <li><a href="https://github.com/SmrfHdl" target="_blank">Phạm Văn Trường</a></li>
                        <li><a href="https://github.com/UETER2226" target="_blank">Đỗ Quang Dũng</a></li>
                        <li><a href="https://github.com/hieu7404" target="_blank">Lê Trung Hiếu</a></li>
                        <li><a href="https://github.com/angWindy" target="_blank">Trần An Thắng</a></li>
                    </ul>
                </div>
            </div>
            <hr>
            <p class="copyright">Alone Wolf Team</p>
        </div>
    </div>

    <!-----------------------------------js for toggle menu------------------------------------------------>
    <script>
        var menuItems=document.getElementById("MenuItems");
        
        MenuItems.style.maxHeight="0px";
        function menutoggle(){
            if(MenuItems.style.maxHeight == "0px"){
                MenuItems.style.maxHeight="200px";
            }
            else{
                MenuItems.style.maxHeight="0px";
            }
        }
    </script>
</body>

</html>